[project]
name = "tws-simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pybind11>=3.0.1",
    "scipy>=1.16.1",
    "sounddevice>=0.5.2",
    "tk>=0.1.0",
]
